# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfrstate < Formula
  desc "Find directories where changed terraform_remote_state data source is used
"
  homepage "https://github.com/suzuki-shunsuke/tfrstate"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.1/tfrstate_darwin_amd64.tar.gz"
      sha256 "b126bb590b12dca5847a67b609c376c56ca558c153d3a3dcff41873e4e1595d7"

      def install
        bin.install "tfrstate"
        generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.1/tfrstate_darwin_arm64.tar.gz"
      sha256 "a043f4da591b115a152e700ae8e8257a6cb8753e2acce6211ca8b33a37387c40"

      def install
        bin.install "tfrstate"
        generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.1/tfrstate_linux_amd64.tar.gz"
        sha256 "639f748d6977436417cf3b92746a8daa57eb2e670af73e0e81dd502be4829941"

        def install
          bin.install "tfrstate"
          generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.1/tfrstate_linux_arm64.tar.gz"
        sha256 "9d67431828cf590a5dcdfa418cb7d8cd7504f36e3ae90344e7fbd5ea30012cb9"

        def install
          bin.install "tfrstate"
          generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/tfrstate --version"
  end
end
