# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfrstate < Formula
  desc "Find directories where changed terraform_remote_state data source is used
"
  homepage "https://github.com/suzuki-shunsuke/tfrstate"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.0/tfrstate_darwin_amd64.tar.gz"
      sha256 "d3bd32a0459b906dbb093c47de2468947b34e28d4e60cc2ce71ea72f1229e55b"

      def install
        bin.install "tfrstate"
        generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.0/tfrstate_darwin_arm64.tar.gz"
      sha256 "3e6c59b76452825fbb54f6aaa4ea4bbd49a922364ee6bfb49125170965af5b22"

      def install
        bin.install "tfrstate"
        generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.0/tfrstate_linux_amd64.tar.gz"
        sha256 "e798e01a56d64cc1696073cabc49000a355e4cfa5cbe0c870e16e243808a0870"

        def install
          bin.install "tfrstate"
          generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.0/tfrstate_linux_arm64.tar.gz"
        sha256 "31479223cf50e2692e47ca548b7c7f4f650eb483128d091024a93b38f38b4cea"

        def install
          bin.install "tfrstate"
          generate_completions_from_executable(bin/"tfrstate", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/tfrstate --version"
  end
end
