# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrstate" do
  name "tfrstate"
  desc "Find directories where changed terraform_remote_state data source is used
"
  homepage "https://github.com/suzuki-shunsuke/tfrstate"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrstate"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v#{version}/tfrstate_darwin_amd64.tar.gz"
      sha256 "37e6c057700a1bb0d39d78f306a073861c0179d462223c1f48f39d4c52faf379"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v#{version}/tfrstate_darwin_arm64.tar.gz"
      sha256 "dd0d60fd5318b2a7ed6cad9aaa87c08f3a3a9ebac160715dd39e6c0426b44755"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v#{version}/tfrstate_linux_amd64.tar.gz"
      sha256 "70a3e2ccc4c50107c4d678d6263726ec15c054642d808de964e95890c2a33608"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v#{version}/tfrstate_linux_arm64.tar.gz"
      sha256 "88c0840661890886ab0616726a6ebbdca47368cb1597702cebd2195d71f82d3c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrstate"]
    end
  end

  # No zap stanza required
end
