# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrstate" do
  desc "Find directories where changed terraform_remote_state data source is used
"
  homepage "https://github.com/suzuki-shunsuke/tfrstate"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrstate"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.7/tfrstate_darwin_amd64.tar.gz"
      sha256 "dbccbd2d9f1b55fd1ebdfdcef8465cfa0fb355fe6bf96f4ff6a94a3f624b8914"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.7/tfrstate_darwin_arm64.tar.gz"
      sha256 "4c3c97b9abf4d112d5226a65b72098399890c60146d6fc1e8879e0b2f0665929"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.7/tfrstate_linux_amd64.tar.gz"
      sha256 "00e258a312e5a582a0dd396a11e47b278d5b8f2ea0684f3813dc85426b034dd5"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfrstate/releases/download/v0.1.7/tfrstate_linux_arm64.tar.gz"
      sha256 "aafe9deddb1fd0e64f36b944cb27ddb3ad9d7b08097c97a94aa6655a62d9e8ac"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrstate"]
    end
  end

  # No zap stanza required
end
